export const FORM_ACTION = {
  FIRST_NAME_INPUT: "FIRST_NAME_INPUT",
  LAST_NAME_INPUT: "LAST_NAME_INPUT",
  PHONE_INPUT: "PHONE_INPUT",
  EMAIL_INPUT: "EMAIL_INPUT",
  STREET_INPUT: "STREET_INPUT",
  CITY_INPUT: "CITY_INPUT",
  STATE_INPUT: "STATE_INPUT",
  POSTAL_INPUT: "POSTAL_INPUT",
  COUNTRY_INPUT: "COUNTRY_INPUT",
  INSTRUCTIONS_INPUT: "INSTRUCTIONS_INPUT",
};
